### ISSUE TITLE
Theta/alpha ration

### ISSUE THREAD

**Issue by LeilaNS** [fraimondo/lg_sleep_paper#1]
Dear Federico,
I am using MNE-Python to process my MEG data (resting-state), and I would like to compute the theta/alpha ratio as shown in Figure 2 of your paper. Could you kindly advise which specific part of the code I should use ?
Thank you for your help.
Best,
Leila 
Neurospin MEG

**Comment by fraimondo** [comment]
Hi Leila!

Indeed the whole code is in this repository.

Basically you'll need this all of these lines:

https://github.com/fraimondo/lg_sleep_paper/blob/017cfc12db49f752afdb71723b1694bdb04b649c/lib/markers.py#L21-L33

https://github.com/fraimondo/lg_sleep_paper/blob/017cfc12db49f752afdb71723b1694bdb04b649c/lib/markers.py#L115-L116

You can then `fit` that marker and then you'll need to summarize/reduce this to scalar values or whatever you want, using something like this:
https://github.com/fraimondo/lg_sleep_paper/blob/017cfc12db49f752afdb71723b1694bdb04b649c/lib/markers.py#L385-L393

**Comment by LeilaNS** [comment]
Thank you for your quick response. Could you please clarify if the theta/alpha ratio in your analysis was computed over all MEG sensors or just the occipital sensors? I guess that scalp_roi contains the region of interest. Could you explain how it was selected or initialized? Also, does Figure 2 show the theta/alpha ratio averaged over all sensors in the scalp_roi?

**Comment by fraimondo** [comment]
The ROIs are defined here:

https://github.com/fraimondo/lg_sleep_paper/blob/017cfc12db49f752afdb71723b1694bdb04b649c/lib/constants.py#L535-L547

In the same file you can find the channels/sensors names.

**Comment by LeilaNS** [comment]
Dear Fed,
Thank you for your message. I run these lines as you recommanded 
```

############### Load Epochs
epochs  = mne.read_epochs(epo_in, preload=True) 
epochs.pick_types(meg='mag')

psds_params = dict(n_fft=4096, n_overlap=100, n_jobs=1, nperseg=128)
base_psd = PowerSpectralDensityEstimator(
    psd_method='welch', tmin=None, tmax=0.6, fmin=1., fmax=80.,
    psd_params=psds_params, comment='default')

theta_pre = PowerSpectralDensity(
    estimator=base_psd, fmin=4., fmax=8., normalize=False,
    comment='theta')

alpha_pre = PowerSpectralDensity(
    estimator=base_psd, fmin=8., fmax=12., normalize=False,
    comment='alpha')

m_list = [
    Ratio(numerator=theta_pre, denominator=alpha_pre,
          comment='theta_alpha')
]
mc = Markers(m_list)
mc.fit(epochs)

reduction_params = {} 
epochs_picks = None
epochs_fun = np.mean
channels_fun = np.std

reduction_params['Ratio/post_theta_alpha'] = {
        'reduction_func':
            [{'axis': 'frequency', 'function': np.sum},
             {'axis': 'channels', 'function': channels_fun},
             {'axis': 'epochs', 'function': epochs_fun}],
        'picks': {
            'epochs': epochs_picks,
            'channels': config.significant_magsens}}

reduction_params['Ratio/theta_alpha'] = \
        reduction_params['Ratio/post_theta_alpha']

mc.reduce_to_scalar(marker_params=reduction_params['Ratio/theta_alpha'])
mc.reduce_to_scalar(marker_params=reduction_params)
```

But at 2 last lines I got an error : 
  ```
File "C:\Users\lazizi\.conda\envs\mne\lib\site-packages\nice\collection.py", line 230, in _check_marker_params_keys
    raise ValueError('Your marker_params is inconsistent with '

ValueError: Your marker_params is inconsistent with the elements in this feature collection: reduction_func is not a valid feature or class
```
So something is wrong with the reduction_params. My goal is to use the same reduction_params as in your paper.
Thnak you for your help.

**Comment by fraimondo** [comment]
Try removing the `post_theta_alpha` that is not needed.

```
reduction_params['Ratio/theta_alpha'] = {
        'reduction_func':
            [{'axis': 'frequency', 'function': np.sum},
             {'axis': 'channels', 'function': channels_fun},
             {'axis': 'epochs', 'function': epochs_fun}],
        'picks': {
            'epochs': epochs_picks,
            'channels': config.significant_magsens}}
```

However, since you are only interested in one marker, there's no need for the marker collection.

You can just do something like this:

```Python
epochs  = mne.read_epochs(epo_in, preload=True) 
epochs.pick_types(meg='mag')

psds_params = dict(n_fft=4096, n_overlap=100, n_jobs=1, nperseg=128)
base_psd = PowerSpectralDensityEstimator(
    psd_method='welch', tmin=None, tmax=0.6, fmin=1., fmax=80.,
    psd_params=psds_params, comment='default')

theta_pre = PowerSpectralDensity(
    estimator=base_psd, fmin=4., fmax=8., normalize=False,
    comment='theta')

alpha_pre = PowerSpectralDensity(
    estimator=base_psd, fmin=8., fmax=12., normalize=False,
    comment='alpha')

ratio = Ratio(
    numerator=theta_pre, denominator=alpha_pre,
    comment='theta_alpha')

ratio.fit(epochs)

scalar_values = ratio.reduce_to_scalar(
    reduction_func=[
        {'axis': 'frequency', 'function': np.sum},
        {'axis': 'channels', 'function': np.mean},
        {'axis': 'epochs', 'function': np.mean}],
    picks={
        'epochs': None,
        'channels': config.significant_magsens
    }
)
````

**Comment by LeilaNS** [comment]
I've just modified slightly your code 
`
reduction_func=[
        {'axis': 'frequency', 'function': np.sum},
        {'axis': 'channels', 'function': np.mean},
        {'axis': 'epochs', 'function': np.mean}
        ]
for ii in range(len(epochs)):
    picks={
            'epochs':[ii],
            'channels':my_channels
        }
    X[ii, :] = ratio.reduce_to_scalar(reduction_func,picks)
    print( X[ii, :])`
And I got the theta_alpha ratio vectors. 
Thank you for your help
